CREATE TABLE IF NOT EXISTS PERSON(
  PERSON_ID CHAR(36) PRIMARY KEY,
  PREFIX VARCHAR(16),
  FIRST_NAME VARCHAR(64) NOT NULL,
  MIDDLE_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  SUFFIX VARCHAR(16)
);

CREATE TABLE IF NOT EXISTS EMAIL_ADDRESS (
  EMAIL_ADDRESS_ID CHAR(36) PRIMARY KEY,
  PERSON_ID CHAR(36)     NOT NULL,
  EMAIL     VARCHAR(256) NOT NULL,
  CONSTRAINT FK_EMAIL_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID),
  CONSTRAINT UQ_EMAIL_ADDRESS UNIQUE (EMAIL)
);

CREATE TABLE IF NOT EXISTS ADDRESS (
  ADDRESS_ID CHAR(36) PRIMARY KEY,
  PERSON_ID CHAR(36)     NOT NULL,
  STREET    VARCHAR(128) NOT NULL,
  CITY      VARCHAR(64)  NOT NULL,
  STATE     VARCHAR(16),
  ZIP_CODE  VARCHAR(16)  NOT NULL,
  CONSTRAINT FK_ADDRESS_PERSON FOREIGN KEY(PERSON_ID) REFERENCES PERSON(PERSON_ID)
);

CREATE TABLE IF NOT EXISTS PHONE_NUMBER (
  PHONE_NUMBER_ID CHAR(36) PRIMARY KEY,
  PERSON_ID CHAR(36) NOT NULL,
  COUNTRY_CODE VARCHAR(10),
  AREA_CODE VARCHAR(16),
  PHONE_NUMBER VARCHAR(32) NOT NULL,
  CONSTRAINT FK_PHONE_PERSON FOREIGN KEY(PERSON_ID) REFERENCES PERSON(PERSON_ID)
);